# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0
  pulumi: pulumi/pulumi@2.0.0
  gcp-cli: circleci/gcp-cli@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  deploy:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/node:16.20
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: 'Authenticate with GCP'
          command: |
            echo $GOOGLE_CREDENTIALS | docker login -u _json_key --password-stdin https://gcr.io
      - run:
          name: 'Install npm dependencies in the infra directory'
          command: npm ci
          working_directory: ./infra
      - run:
          name: 'Install npm dependencies in the app directory'
          command: npm ci
          working_directory: ./app
      - pulumi/login:
          version: 3.89.0
      - run:
          name: 'Preview pulumi changes'
          command: pulumi preview -s linhvuvan2022/poc-compute-engine/dev
          working_directory: ./infra
      - run:
          name: 'Deploy pulumi changes'
          command: pulumi up -s linhvuvan2022/poc-compute-engine/dev -y
          working_directory: ./infra

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - deploy
